### ISSUE TITLE
Webcam not working

### ISSUE THREAD

**Issue by verpejas** [xma/T480-Clover#51]
Hi. I have a T480 in this config:
i7-8550u, MX150, 32GB ram, 1TB Samsung SSD 980, Intel AX210 WiFI

I used itlwm for my wif card, works flawlessly. I have only one issue with this setup, the webcam does not work. The microphone works just fine, but for some reason the webcam shows as not connected. Your clover config seems to be the best one yet, it would be awesome if You could help with the camera situatuon. Camera was working on opencore with efi folder by hexart.

**Comment by xma** [comment]
Hello, 

here camera is working fine 
i don't use it at all but it worked since 1st commit here

could you go in about this mac -> System report -> USB 

It should report an entry with 'Integrated camera'
![usb](https://user-images.githubusercontent.com/548909/159334083-ccd7b3ca-ea32-41f7-9f1d-14e47bed55bf.png)


differences I see this between my repo and hexart 

USBPorts.kext

https://github.com/hexart/T480-OpenCore-Hackintosh/blob/main/EFI/OC/Kexts/USBPorts.kext
HS01 - HS08 and SS01 - SS04

whereas here it's 
HS01 - HS10 and SS01 - SS03

**Comment by xma** [comment]
And with 'Hackintool'
https://github.com/headkaze/Hackintool

in the USB panel
![Uploading hackintool.png…]()

**Comment by verpejas** [comment]
Hi! Here are the screenshots you mentioned. I also attached a screenshot of loaded kexts. The camera is not visible and I seem to have less USB devices listed in hackintool. I used Your EFI config, removed broadcom kexts, injected itlwm and generated my SMBIOS, rest is unmodified. 

I saw a mention that the IR camera requires different USB map. Strangely enough, the microphones (which are integrated into the camera unit) work without any problems. The camera is not deteted in photobooth, chrome camera test, system report and in hackintool too.

![Screenshot 2022-03-21 at 23 42 06](https://user-images.githubusercontent.com/90029304/159375560-91bf8c18-69ff-4323-afcc-95e44ebb299a.png)
![Screenshot 2022-03-21 at 23 45 43](https://user-images.githubusercontent.com/90029304/159375565-c6c6eac2-3491-4241-a36d-816fb01dab32.png)
![Screenshot 2022-03-21 at 23 46 22](https://user-images.githubusercontent.com/90029304/159375572-826b65ad-8260-4319-950e-cac5195b0d9c.png)
